/**
 * @fileoverview Centralized AWS error code constants and types.
 *
 * Provides `AwsErrorCodes` to standardize error `code` values per service and
 * `AwsErrorCode`, a union of all service error codes used across this package.
 */

export const AwsErrorCodes = {
  S3: {
    BUCKET_NOT_FOUND: "S3_BUCKET_NOT_FOUND",
    OBJECT_NOT_FOUND: "S3_OBJECT_NOT_FOUND",
    ACCESS_DENIED: "S3_ACCESS_DENIED",
    THROTTLING: "S3_THROTTLING",
    VALIDATION_ERROR: "S3_VALIDATION_ERROR",
    TIMEOUT: "S3_TIMEOUT",
    INTERNAL_ERROR: "S3_INTERNAL_ERROR",
  },
  DynamoDB: {
    CONDITIONAL_CHECK_FAILED: "DYNAMODB_CONDITIONAL_CHECK_FAILED",
    THROUGHPUT_EXCEEDED: "DYNAMODB_THROUGHPUT_EXCEEDED",
    ITEM_NOT_FOUND: "DYNAMODB_ITEM_NOT_FOUND",
    TRANSACTION_CONFLICT: "DYNAMODB_TRANSACTION_CONFLICT",
    ACCESS_DENIED: "DYNAMODB_ACCESS_DENIED",
    THROTTLING: "DYNAMODB_THROTTLING",
    VALIDATION_ERROR: "DYNAMODB_VALIDATION_ERROR",
    INTERNAL_ERROR: "DYNAMODB_INTERNAL_ERROR",
  },
  Lambda: {
    FUNCTION_NOT_FOUND: "LAMBDA_FUNCTION_NOT_FOUND",
    THROTTLING: "LAMBDA_THROTTLING",
    ACCESS_DENIED: "LAMBDA_ACCESS_DENIED",
    TIMEOUT: "LAMBDA_TIMEOUT",
    VALIDATION_ERROR: "LAMBDA_VALIDATION_ERROR",
    SERVICE_UNAVAILABLE: "LAMBDA_SERVICE_UNAVAILABLE",
    INTERNAL_ERROR: "LAMBDA_INTERNAL_ERROR",
  },
  SQS: {
    QUEUE_NOT_FOUND: "SQS_QUEUE_NOT_FOUND",
    THROTTLING: "SQS_THROTTLING",
    ACCESS_DENIED: "SQS_ACCESS_DENIED",
    MESSAGE_TOO_LARGE: "SQS_MESSAGE_TOO_LARGE",
    TIMEOUT: "SQS_TIMEOUT",
    INTERNAL_ERROR: "SQS_INTERNAL_ERROR",
    VALIDATION_ERROR: "SQS_VALIDATION_ERROR",
  },
  SNS: {
    TOPIC_NOT_FOUND: "SNS_TOPIC_NOT_FOUND",
    THROTTLING: "SNS_THROTTLING",
    ACCESS_DENIED: "SNS_ACCESS_DENIED",
    VALIDATION_ERROR: "SNS_VALIDATION_ERROR",
    INTERNAL_ERROR: "SNS_INTERNAL_ERROR",
  },
  Kinesis: {
    PROVISIONED_THROUGHPUT_EXCEEDED: "KINESIS_PROVISIONED_THROUGHPUT_EXCEEDED",
    THROTTLING: "KINESIS_THROTTLING",
    STREAM_NOT_FOUND: "KINESIS_STREAM_NOT_FOUND",
    ACCESS_DENIED: "KINESIS_ACCESS_DENIED",
    VALIDATION_ERROR: "KINESIS_VALIDATION_ERROR",
    TIMEOUT: "KINESIS_TIMEOUT",
    INTERNAL_ERROR: "KINESIS_INTERNAL_ERROR",
  },
  MSK: {
    THROTTLING: "MSK_THROTTLING",
    CLUSTER_NOT_FOUND: "MSK_CLUSTER_NOT_FOUND",
    ACCESS_DENIED: "MSK_ACCESS_DENIED",
    VALIDATION_ERROR: "MSK_VALIDATION_ERROR",
    TIMEOUT: "MSK_TIMEOUT",
    INTERNAL_ERROR: "MSK_INTERNAL_ERROR",
  },
  CloudWatchLogs: {
    LOG_GROUP_NOT_FOUND: "CLOUDWATCH_LOG_GROUP_NOT_FOUND",
    LOG_STREAM_NOT_FOUND: "CLOUDWATCH_LOG_STREAM_NOT_FOUND",
    THROTTLING: "CLOUDWATCH_LOGS_THROTTLING",
    ACCESS_DENIED: "CLOUDWATCH_LOGS_ACCESS_DENIED",
    VALIDATION_ERROR: "CLOUDWATCH_LOGS_VALIDATION_ERROR",
    SERVICE_UNAVAILABLE: "CLOUDWATCH_LOGS_SERVICE_UNAVAILABLE",
  },
  CloudWatchMetrics: {
    THROTTLING: "CLOUDWATCH_METRICS_THROTTLING",
    LIMIT_EXCEEDED: "CLOUDWATCH_METRICS_LIMIT_EXCEEDED",
    ACCESS_DENIED: "CLOUDWATCH_METRICS_ACCESS_DENIED",
    VALIDATION_ERROR: "CLOUDWATCH_METRICS_VALIDATION_ERROR",
    INTERNAL_ERROR: "CLOUDWATCH_METRICS_INTERNAL_ERROR",
  },
  EventBridge: {
    BUS_NOT_FOUND: "EVENTBRIDGE_BUS_NOT_FOUND",
    RULE_NOT_FOUND: "EVENTBRIDGE_RULE_NOT_FOUND",
    THROTTLING: "EVENTBRIDGE_THROTTLING",
    ACCESS_DENIED: "EVENTBRIDGE_ACCESS_DENIED",
    VALIDATION_ERROR: "EVENTBRIDGE_VALIDATION_ERROR",
  },
  SSM: {
    PARAMETER_NOT_FOUND: "SSM_PARAMETER_NOT_FOUND",
    THROTTLING: "SSM_THROTTLING",
    ACCESS_DENIED: "SSM_ACCESS_DENIED",
  },
  SecretsManager: {
    SECRET_NOT_FOUND: "SECRETSMANAGER_SECRET_NOT_FOUND",
    DECRYPTION_FAILURE: "SECRETSMANAGER_DECRYPTION_FAILURE",
    THROTTLING: "SECRETSMANAGER_THROTTLING",
    ACCESS_DENIED: "SECRETSMANAGER_ACCESS_DENIED",
    VALIDATION_ERROR: "SECRETSMANAGER_VALIDATION_ERROR",
    INTERNAL_ERROR: "SECRETSMANAGER_INTERNAL_ERROR",
  },
  KMS: {
    KEY_NOT_FOUND: "KMS_KEY_NOT_FOUND",
    INVALID_CIPHERTEXT: "KMS_INVALID_CIPHERTEXT",
    THROTTLING: "KMS_THROTTLING",
    ACCESS_DENIED: "KMS_ACCESS_DENIED",
    INTERNAL_ERROR: "KMS_INTERNAL_ERROR",
  },
  STS: {
    AUTHENTICATION_ERROR: "STS_AUTHENTICATION_ERROR",
    ACCESS_DENIED: "STS_ACCESS_DENIED",
    THROTTLING: "STS_THROTTLING",
    VALIDATION_ERROR: "STS_VALIDATION_ERROR",
    TIMEOUT: "STS_TIMEOUT",
    INTERNAL_ERROR: "STS_INTERNAL_ERROR",
  },
  ApiGateway: {
    NOT_FOUND: "APIGW_NOT_FOUND",
    THROTTLING: "APIGW_THROTTLING",
    ACCESS_DENIED: "APIGW_ACCESS_DENIED",
    VALIDATION_ERROR: "APIGW_VALIDATION_ERROR",
    TIMEOUT: "APIGW_TIMEOUT",
    INTERNAL_ERROR: "APIGW_INTERNAL_ERROR",
  },
  StepFunctions: {
    EXECUTION_NOT_FOUND: "SFN_EXECUTION_NOT_FOUND",
    STATE_MACHINE_NOT_FOUND: "SFN_STATE_MACHINE_NOT_FOUND",
    THROTTLING: "SFN_THROTTLING",
    ACCESS_DENIED: "SFN_ACCESS_DENIED",
    VALIDATION_ERROR: "SFN_VALIDATION_ERROR",
    INTERNAL_ERROR: "SFN_INTERNAL_ERROR",
  },
} as const;

/**
 * Helper type to extract all nested values from a nested object.
 */
type ValueOf<T> = T[keyof T];

/**
 * Union type of all AWS error codes across all services.
 */
export type AwsErrorCode = ValueOf<ValueOf<typeof AwsErrorCodes>>;
